### ISSUE TITLE
`weather-dl` : pipeline crashes/not terminated gracefully when there is no chunk to download.

### ISSUE THREAD

**Issue by mahrsee1997** [google/weather-tools#271]
### Problem:
Provided a config to download N chunks & if all of them are already downloaded, these files will be skipped -- which is intended behaviour but soon after that pipeline crashes/not terminated gracefully.

### Error logs:
```
INFO 22-12-16 07:21:18 download_pipeline.partition: file gs://XXXX.nc found, skipping.
INFO 22-12-16 07:21:18 download_pipeline.partition: file gs://XXXX.nc found, skipping.
INFO 22-12-16 07:21:18 download_pipeline.partition: file gs://XXXX.nc found, skipping.
INFO 22-12-16 07:21:18 download_pipeline.partition: file gs://XXXX.nc found, skipping.
Traceback (most recent call last):
  File "weather_dl/weather-dl", line 76, in <module>
    cli(['--extra_package', pkg_archive])
  File "/usr/local/google/home/mahrsee/weather-tools/weather_dl/download_pipeline/__init__.py", line 20, in cli
    pipeline(run(sys.argv + extra))
  File "/usr/local/google/home/mahrsee/weather-tools/weather_dl/download_pipeline/pipeline.py", line 116, in pipeline
    (
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/pipeline.py", line 597, in __exit__
    self.result = self.run()
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/pipeline.py", line 574, in run
    return self.runner.run_pipeline(self, self._options)
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 199, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 212, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 442, in run_stages
    bundle_results = self._execute_bundle(
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 770, in _execute_bundle
    self._run_bundle(
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 999, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/usr/local/google/home/mahrsee/miniconda3/envs/weather-tools/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1393, in process_bundle
    for ix, part in enumerate(input.partition(self._num_workers)):
AttributeError: 'NoneType' object has no attribute 'partition'
```

**Comment by mahrsee1997** [comment]
Closing this issue as it was a user error. 
I was running the tools in the local runner specifying `--direct_num_workers 20`. In the normal scenario this is not reproducible in local runner & dataflow runner.
